// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
    },
    {
      type: 'category',
      label: 'Physical AI Foundations',
      className: 'sidebar-item-foundations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'physical-ai-foundations',
        },
      ],
    },
    {
      type: 'category',
      label: 'Humanoid Robotics Fundamentals',
      className: 'sidebar-item-robotics',
      items: [
        {
          type: 'autogenerated',
          dirName: 'humanoid-robotics-fundamentals',
        },
      ],
    },
    {
      type: 'category',
      label: 'Control Systems',
      className: 'sidebar-item-control',
      items: [
        {
          type: 'autogenerated',
          dirName: 'control-systems',
        },
      ],
    },
    {
      type: 'category',
      label: 'Perception and Sensor Fusion',
      className: 'sidebar-item-perception',
      items: [
        {
          type: 'autogenerated',
          dirName: 'perception',
        },
      ],
    },
    {
      type: 'category',
      label: 'Learning and Intelligence',
      className: 'sidebar-item-learning',
      items: [
        {
          type: 'autogenerated',
          dirName: 'learning-intelligence',
        },
      ],
    },
    {
      type: 'category',
      label: 'System Integration and Real-World Applications',
      className: 'sidebar-item-integration',
      items: [
        {
          type: 'autogenerated',
          dirName: 'system-integration',
        },
      ],
    },
    {
      type: 'category',
      label: 'The Robotic Nervous System (ROS 2)',
      className: 'sidebar-item-ros',
      items: [
        {
          type: 'autogenerated',
          dirName: 'robotic-nervous-system',
        },
      ],
    },
    {
      type: 'category',
      label: 'The Digital Twin (Gazebo & Unity)',
      className: 'sidebar-item-digital-twin',
      items: [
        {
          type: 'autogenerated',
          dirName: 'digital-twin',
        },
      ],
    },
    {
      type: 'category',
      label: 'The AI-Robot Brain (NVIDIA Isaac)',
      className: 'sidebar-item-ai-brain',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ai-robot-brain',
        },
      ],
    },
    {
      type: 'category',
      label: 'Vision-Language-Action (VLA) + Capstone',
      className: 'sidebar-item-capstone',
      items: [
        {
          type: 'autogenerated',
          dirName: 'vla-capstone',
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced Documentation',
      className: 'sidebar-item-advanced',
      items: [
        {
          type: 'autogenerated',
          dirName: 'advanced-docs',
        },
      ],
    },
  ],
};

module.exports = sidebars;