// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
    },
    {
      type: 'category',
      label: 'Physical AI Foundations',
      items: [
        {
          type: 'autogenerated',
          dirName: 'physical-ai-foundations',
        },
      ],
    },
    {
      type: 'category',
      label: 'Humanoid Robotics Fundamentals',
      items: [
        {
          type: 'autogenerated',
          dirName: 'humanoid-robotics-fundamentals',
        },
      ],
    },
    {
      type: 'category',
      label: 'Control Systems',
      items: [
        {
          type: 'autogenerated',
          dirName: 'control-systems',
        },
      ],
    },
    {
      type: 'category',
      label: 'Perception and Sensor Fusion',
      items: [
        {
          type: 'autogenerated',
          dirName: 'perception',
        },
      ],
    },
    {
      type: 'category',
      label: 'Learning and Intelligence',
      items: [
        {
          type: 'autogenerated',
          dirName: 'learning-intelligence',
        },
      ],
    },
    {
      type: 'category',
      label: 'System Integration and Real-World Applications',
      items: [
        {
          type: 'autogenerated',
          dirName: 'system-integration',
        },
      ],
    },
    {
      type: 'category',
      label: 'The Robotic Nervous System (ROS 2)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'robotic-nervous-system',
        },
      ],
    },
    {
      type: 'category',
      label: 'The Digital Twin (Gazebo & Unity)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'digital-twin',
        },
      ],
    },
    {
      type: 'category',
      label: 'The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ai-robot-brain',
        },
      ],
    },
    {
      type: 'category',
      label: 'Vision-Language-Action (VLA) + Capstone',
      items: [
        {
          type: 'autogenerated',
          dirName: 'vla-capstone',
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced Documentation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'advanced-docs',
        },
      ],
    },
  ],
};

module.exports = sidebars;