// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'index',
    },
    {
      type: 'category',
      label: 'The Robotic Nervous System (ROS 2)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'robotic-nervous-system',
        },
      ],
    },
    {
      type: 'category',
      label: 'The Digital Twin (Gazebo & Unity)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'digital-twin',
        },
      ],
    },
    {
      type: 'category',
      label: 'The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ai-robot-brain',
        },
      ],
    },
    {
      type: 'category',
      label: 'Vision-Language-Action (VLA) + Capstone',
      items: [
        {
          type: 'autogenerated',
          dirName: 'vla-capstone',
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced Documentation',
      items: [
        {
          type: 'autogenerated',
          dirName: 'advanced-docs',
        },
      ],
    },
  ],
};

module.exports = sidebars;